export enum DANGER_METER {
  BALANCED = "BALANCED",
  UNPREDICTABLE = "UNPREDICTABLE",
  TEAM_PLAYER = "TEAM_PLAYER",
  AGGRESIVE = "AGGRESIVE",
  DEFENSIVE = "DEFENSIVE",
  TECHNICAL = "TECHNICAL",
}

export enum ACTION_TYPES {
  NETWORK = "NETWORK",
  ITEM = "ITEM",
  GIT = "GIT",
  ATTACK = "ATTACK",
  DEFENSE = "DEFENSE",
  SURRENDER = "SURRENDER",
  BATTERY = "BATTERY",
  GLOBAL = "GLOBAL",
}

export enum OPERATING_SYSTEM {
  MAC = "MAC",
  WINDOWS = "WINDOWS",
  LINUX = "LINUX",
}

export enum RANK {
  JUNIOR = "JUNIOR",
  MEDIER = "MEDIER",
  SENIOR = "SENIOR",
  LEAD_DEVELOPER = "LEAD DEVELOPER",
  SITE_RELIABILITY_ENGINEER = "SITE RELIABILITY ENGINEER",
  TECH_LEAD = "TECH LEAD",
  CTO = "CTO",
}

export enum JOB_POSITION {
  FRONTEND = "FRONTEND_DEVELOPER",
  BACKEND = "BACKEND_DEVELOPER",
  FULLSTACK = "FULLSTACK_DEVELOPER",
  DEVOPS = "DEVOPS",
  SOFTWARE_ENGINEER = "SOFTWARE_ENGINEER",
  RED_TEAMER = "RED_TEAMER",
  BLUE_TEAMER = "BLUE_TEAMER",
  PURPLE_TEAMER = "PURPLE_TEAMER",
}

export enum PROGRAMMING_LANGUAGE {
  PHP = "PHP",
  RUBY = "RUBY",
  PYTHON = "PYTHON",
  JAVASCRIPT = "JAVASCRIPT",
  TYPESCRIPT = "TYPESCRIPT",
  JAVA = "JAVA",
  C = "C",
  CPLUS = "C++",
  CSHARP = "C#",
  SCALA = "SCALA",
  ELIXIR = "ELIXIR",
}
